categories:
  memory:
    enabled: true
    url: https://www.kabum.com.br/hardware/memoria-ram/ddr-5?page_number=1&page_size=20&facet_filters=eyJoYXNfb3Blbl9ib3giOlsidHJ1ZSJdfQ==&sort=most_searched
    filters:
      min_capacity_gb: 16
      max_price: 1300.0
      exclude_notebook: true
      exclude_keywords:
      - NOTEBOOK
      - LAPTOP
      - SO-DIMM
      - SODIMM
      - MOBILE
      - PARA NOTEBOOK
      - PARA LAPTOP
      - XMP
  psu:
    enabled: true
    url: https://www.kabum.com.br/hardware/fontes?page_number=1&page_size=20&facet_filters=eyJoYXNfb3Blbl9ib3giOlsidHJ1ZSJdfQ==&sort=most_searched
    filters:
      min_watts: 750
      efficiency: GOLD
      max_price: null
  cpu:
    enabled: true
    url: https://www.kabum.com.br/hardware/processadores/processador-amd?page_number=1&page_size=20&facet_filters=eyJoYXNfb3Blbl9ib3giOlsidHJ1ZSJdfQ==&sort=most_searched
    filters:
      brand: AMD
      series:
      - 7xxx
      - 9xxx
      max_price: null
settings:
  check_interval_minutes: 10
  alert_cooldown_hours: 3
  enable_alerts: true
