items:
- id: cruise-royal-caribbean-greece-2026
  name: Cruzeiro Royal Caribbean - Grécia 7 Noites (05-12 Set/2026)
  category: cruise
  desired_price: 10000.0
  enabled: true
  urls:
  - store: royalcaribbean
    url: https://www.royalcaribbean.com/bra/pt/checkout/summary?groupId=EX07BLQ-2504783051&packageCode=EX07M799&sailDate=2026-09-05&country=BRA&selectedCurrencyCode=BRL&shipCode=EX&cabinClassType=INTERIOR&roomIndex=0&r0a=2&r0c=0&r0b=n&r0l=395356337&r0r=n&r0s=n&r0q=n&r0t=n&r0d=INTERIOR&r0D=n&rgVisited=true&r0C=y&r0e=ZI&r0f=ZI&r0g=BESTRATE&r0h=r&r0p=3&r0z=n&r0m=y
- id: motherboard-asus-tuf-b650m-e-wifi
  name: Placa-Mãe ASUS TUF Gaming B650M-E WiFi AMD AM5 B650 DDR5
  category: motherboard
  desired_price: 1200.0
  enabled: true
  urls:
  - store: kabum
    url: https://www.kabum.com.br/produto/523145/placa-mae-asus-tuf-gaming-b650m-e-wifi-amd-am5-b650-ddr5-preto-90mb1fv0-m0eay0
  - store: pichau
    url: https://www.pichau.com.br/placa-mae-asus-tuf-gaming-b650m-e-ddr5-socket-amd-am5-m-atx-chipset-amd-b650-tuf-gaming-b650m-e
  - store: inpower
    url: https://www.inpower.com.br/placa-mae-asus-tuf-gaming-para-amd-am5-b650m-e-wifi-4xddr5-matx-90mb1fv0-m0eay0-p1026920
- id: motherboard-gigabyte-b650m-aorus-elite-ax
  name: Placa-Mãe Gigabyte B650M Aorus Elite AX AMD AM5 Micro-ATX DDR5 Wi-Fi Bluetooth
  category: motherboard
  desired_price: 1200.0
  enabled: true
  urls:
  - store: kabum
    url: https://www.kabum.com.br/produto/390275/placa-mae-gigabyte-b650m-aorus-elite-ax-amd-micro-atx-ddr5-wi-fi-bluetooth-b650m-aorus-elite-ax
- id: motherboard-asus-tuf-b650em-plus
  name: Placa-Mãe ASUS TUF B650EM Plus AMD AM5 M-ATX DDR5 WiFi 6E Bluetooth
  category: motherboard
  desired_price: 1200.0
  enabled: true
  urls:
  - store: kabum
    url: https://www.kabum.com.br/produto/871302/placa-mae-asus-tuf-b650em-plus-amd-am5-m-atx-ddr5-wifi-6e-bluetooth-preto-90mb1lu0
  - store: inpower
    url: https://www.inpower.com.br/placa-mae-asus-tuf-gaming-b850m-plus-chipset-b850-amd-am5-matx-ddr5-90mb1ix0-m0eay0-p1168141
  - store: amazon
    url: https://www.amazon.com.br/ASUS-Gaming-B850M-PLUS-Compat%C3%ADvel-Mem%C3%B3ria/dp/B0G1HPV39B/ref=sr_1_5?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=23A6S0QHR2AQE&dib=eyJ2IjoiMSJ9.0Cq3kzWQRTya2PS4r-ZTI-eAehaafrtKHe6pQ9cjpxQTzsE8sTY-MAfTISAGbuq8PGIdqP1Qbp52J-TObDLsFFFyxo-S67DgOgEfq234-W8l7I8l9M-lDe0FEtcGyhnBLJjR1dZxtsQOFzO2tyQAPuBsxlcHoYgyOQAIEMwy5yTpaVbJOiPtOqHO-Z7OUS8K1HfK9nCAV1Y2IR4bdds-sby_7LJDOjIIs253JWQ0R3sueyyC-m0xd5ds09GK9NSK7pdp-XEHjHxxu77If1LrKgoeOBcPENvd5XMj4Aju8Eg.DVwmYXCB8vOn10UMskUm8aPRXpdXhf02F0kn3FA1sa0&dib_tag=se&keywords=Placa-M%C3%A3e+ASUS+TUF+B850EM+Plus+AMD+AM5+M-ATX+DDR5+WiFi+6E+Bluetooth&qid=1763587842&sprefix=placa-m%C3%A3e+asus+tuf+b850em+plus+amd+am5+m-atx+ddr5+wifi+6e+bluetooth%2Caps%2C188&sr=8-5&ufe=app_do%3Aamzn1.fos.95de73c3-5dda-43a7-bd1f-63af03b14751
  - store: kabum
    url: https://www.kabum.com.br/produto/725578/placa-mae-asus-tuf-b850m-plus-wifi-amd-am5-m-atx-ddr5-wi-fi-6e-preto-tuf-gaming-b850m-plus-wifi
- id: memory-xpg-lancer-rgb-32gb
  name: Memória XPG Lancer RGB 32GB (2x16GB) DDR5 6000MHz CL30 Preta
  category: memory
  desired_price: 900.0
  enabled: true
  urls:
  - store: kabum
    url: https://www.kabum.com.br/produto/380742/memoria-xpg-lancer-rgb-32gb-2x16gb-6000mhz-ddr5-cl30-preta-ax5u6000c3016g-dclarbk
  - store: pichau
    url: https://www.pichau.com.br/memoria-xpg-lancer-rgb-32gb-2x16gb-ddr5-6000mhz-preta-ax5u6000c3016g-dclarbk
- id: memory-ddr5-8gb-6000mhz-cl30
  name: Memória DDR5 8GB 6000MHz CL30
  category: memory
  desired_price: 300.0
  enabled: true
  urls: []
- id: memory-ddr5-16gb-6000mhz-cl30
  name: Memória DDR5 16GB 6000MHz CL30
  category: memory
  desired_price: 500.0
  enabled: true
  urls: []
- id: memory-ddr5-32gb-6000mhz-cl30
  name: Memória DDR5 32GB 6000MHz CL30
  category: memory
  desired_price: 900.0
  enabled: true
  urls: []
